"use client";
import{useMemo,useState}from"react";import{supabase}from"../lib/supabase";
type PlanStep={title:string;daysBefore:number;selected:boolean};const templates:Record<string,PlanStep[]>={
"College application":[{title:"Confirm requirements and official deadline",daysBefore:56,selected:true},{title:"Request recommendation letters",daysBefore:42,selected:true},{title:"Complete activities and resume details",daysBefore:35,selected:true},{title:"Finish first essay draft",daysBefore:28,selected:true},{title:"Complete supplemental responses",daysBefore:21,selected:true},{title:"Review application with a trusted adult",daysBefore:14,selected:true},{title:"Proofread and verify every section",daysBefore:7,selected:true},{title:"Submit before the final day",daysBefore:3,selected:true}],
"Scholarship application":[{title:"Verify eligibility and required materials",daysBefore:35,selected:true},{title:"Request transcripts or recommendations",daysBefore:28,selected:true},{title:"Brainstorm the essay response",daysBefore:21,selected:true},{title:"Finish the first essay draft",daysBefore:14,selected:true},{title:"Revise and proofread",daysBefore:7,selected:true},{title:"Submit and save confirmation",daysBefore:2,selected:true}],
"SAT or ACT":[{title:"Confirm official registration and test date",daysBefore:70,selected:true},{title:"Complete a diagnostic using official materials",daysBefore:56,selected:true},{title:"Begin weekly study schedule",daysBefore:49,selected:true},{title:"Complete an official practice test",daysBefore:28,selected:true},{title:"Review weakest areas",daysBefore:21,selected:true},{title:"Complete final official practice test",daysBefore:10,selected:true},{title:"Prepare the test-day checklist",daysBefore:3,selected:true}],
"Interview":[{title:"Research the organization and interviewer",daysBefore:14,selected:true},{title:"Draft questions to ask",daysBefore:10,selected:true},{title:"Practice STAR responses",daysBefore:7,selected:true},{title:"Complete a practice interview",daysBefore:4,selected:true},{title:"Confirm technology, location, and clothing",daysBefore:2,selected:true},{title:"Send a thank-you note",daysBefore:-1,selected:true}],
"FAFSA or financial aid":[{title:"Confirm the official opening date and requirements",daysBefore:42,selected:true},{title:"Identify required contributors",daysBefore:35,selected:true},{title:"Gather information securely offline",daysBefore:28,selected:true},{title:"Create required StudentAid.gov accounts",daysBefore:21,selected:true},{title:"Complete and carefully review the form",daysBefore:10,selected:true},{title:"Submit and save official confirmation",daysBefore:3,selected:true},{title:"Check processing status",daysBefore:-7,selected:true}],
};
const shift=(date:string,days:number)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)};
export function BackwardPlanner({userId}:{userId:string}){const[type,setType]=useState("College application"),[goal,setGoal]=useState(""),[deadline,setDeadline]=useState(""),[choices,setChoices]=useState<Record<string,boolean>>({}),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);const preview=useMemo(()=>deadline?templates[type].map((step,index)=>({...step,key:`${type}-${index}`,date:shift(deadline,step.daysBefore),selected:choices[`${type}-${index}`]??step.selected})):[],[choices,deadline,type]);function toggle(key:string,value:boolean){setChoices({...choices,[key]:value})}async function save(){const selected=preview.filter(x=>x.selected);if(!goal.trim()||!deadline)return setMessage("Enter a goal name and final date.");if(!selected.length)return setMessage("Select at least one preparation step.");setSaving(true);const rows=selected.map((step,index)=>({user_id:userId,title:`${goal.trim()}: ${step.title}`,category:type,due_date:step.date,notes:`Generated from the ${type} backward-planning template. Verify the final date and adjust this preparation milestone as needed.`,position:1000+index,completed:false}));const{error}=await supabase.from("student_steps").insert(rows);setSaving(false);setMessage(error?error.message:`${rows.length} preparation milestones added to My Path.`)}
return <section className="backward-planner" id="backward-planner"><div className="backward-heading"><div><span className="kicker dark">BACKWARD PLANNER</span><h2>Turn one deadline into manageable steps.</h2><p>Start with an official final date, preview a preparation schedule, and save only the milestones that fit.</p></div></div><div className="backward-grid"><article className="backward-form"><label>Goal type<select value={type} onChange={e=>{setType(e.target.value);setChoices({})}}>{Object.keys(templates).map(x=><option key={x}>{x}</option>)}</select></label><label>School, scholarship, test, or goal name<input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Example: State University application"/></label><label>Official final date<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><button onClick={save} disabled={saving||!deadline||!goal.trim()}>{saving?"Adding milestones...":"Add selected steps to My Path"}</button>{message&&<p role="status" className="form-message">{message}</p>}<p className="official-note">Templates are general planning suggestions. They do not change official requirements or deadlines.</p></article><article className="backward-preview"><h3>Preparation schedule</h3>{preview.length?preview.map(step=><label key={step.key} className={step.date<new Date().toISOString().slice(0,10)?"past-step":""}><input type="checkbox" checked={step.selected} onChange={e=>toggle(step.key,e.target.checked)}/><span><b>{step.title}</b><time>{new Date(`${step.date}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}</time>{step.date<new Date().toISOString().slice(0,10)&&<small>This suggested date has passed. Adjust it after saving.</small>}</span></label>):<p>Enter the final date to preview a schedule.</p>}</article></div></section>}
