"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
type App={college_name:string;status:string;deadline:string|null};type Offer={school_name:string;estimated_cost:number;grants:number;scholarships:number;work_study:number;loans:number;status:string};type Decision={school_name:string;academics:number;affordability:number;campus_life:number;location_fit:number;career_fit:number;notes:string};
const blank=(school_name:string):Decision=>({school_name,academics:3,affordability:3,campus_life:3,location_fit:3,career_fit:3,notes:""});
export function CollegeDecisionWorkspace({userId}:{userId:string}){const[apps,setApps]=useState<App[]>([]),[offers,setOffers]=useState<Offer[]>([]),[decisions,setDecisions]=useState<Decision[]>([]),[message,setMessage]=useState("");
useEffect(()=>{Promise.all([supabase.from("college_applications").select("college_name,status,deadline").eq("user_id",userId),supabase.from("financial_aid_offers").select("school_name,estimated_cost,grants,scholarships,work_study,loans,status").eq("user_id",userId),supabase.from("student_college_decisions").select("school_name,academics,affordability,campus_life,location_fit,career_fit,notes").eq("user_id",userId)]).then(([a,o,d])=>{setApps((a.data??[])as App[]);setOffers((o.data??[])as Offer[]);setDecisions((d.data??[])as Decision[])})},[userId]);
const schools=useMemo(()=>Array.from(new Set([...apps.map(x=>x.college_name),...offers.map(x=>x.school_name)])).map(name=>({name,application:apps.find(x=>x.college_name===name),offer:offers.find(x=>x.school_name===name),decision:decisions.find(x=>x.school_name===name)??blank(name)})),[apps,offers,decisions]);
const score=(d:Decision)=>d.academics+d.affordability+d.campus_life+d.location_fit+d.career_fit;function change(name:string,patch:Partial<Decision>){setDecisions(current=>{const found=current.find(x=>x.school_name===name);return found?current.map(x=>x.school_name===name?{...x,...patch}:x):[...current,{...blank(name),...patch}]})}
async function save(d:Decision){const{error}=await supabase.from("student_college_decisions").upsert({user_id:userId,...d,updated_at:new Date().toISOString()},{onConflict:"user_id,school_name"});setMessage(error?error.message:`${d.school_name} decision notes saved.`)}
return <section className="decision-workspace" id="college-decisions"><div className="decision-heading"><span className="kicker dark">COLLEGE DECISION WORKSPACE</span><h2>Compare the whole picture.</h2><p>Use personal priorities alongside verified admission and financial-aid information. A higher fit score is an organization aid, not a recommendation.</p></div>{schools.length?<div className="decision-table"><div className="decision-row decision-head"><b>School</b><b>Admission</b><b>Estimated net price</b><b>My fit</b><b>Notes</b></div>{schools.sort((a,b)=>score(b.decision)-score(a.decision)).map(({name,application,offer,decision})=>{const gift=(offer?.grants??0)+(offer?.scholarships??0),net=offer?Math.max(0,offer.estimated_cost-gift):null;return <div className="decision-row" key={name}><div><h3>{name}</h3><small>{application?.deadline?`Decision/application date: ${application.deadline}`:"Verify the decision deadline"}</small></div><div><b>{application?.status??"Not tracked"}</b></div><div>{net===null?<a href="#financial-aid">Add aid offer</a>:<><b>${net.toLocaleString()}</b><small>Cost minus grants and scholarships</small><small>Loans listed: ${(offer?.loans??0).toLocaleString("en-US",{style:"currency",currency:"USD"})}</small></>}</div><div className="fit-ratings">{([['academics','Academics'],['affordability','Affordability'],['campus_life','Campus life'],['location_fit','Location'],['career_fit','Career fit']]as const).map(([key,label])=><label key={key}>{label}<select value={decision[key]} onChange={e=>change(name,{[key]:Number(e.target.value)})}>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x}</option>)}</select></label>)}<b>{score(decision)}/25 personal fit</b></div><div><textarea maxLength={5000} value={decision.notes} onChange={e=>change(name,{notes:e.target.value})} placeholder="What matters to me? What must I verify?"/><button onClick={()=>save(decision)}>Save</button></div></div>})}</div>:<div className="empty-decision"><h3>Add a college application or financial-aid offer to begin.</h3><a href="#applications">Open application tracker</a></div>}{message&&<p className="form-message" role="status">{message}</p>}<p className="official-note">Confirm costs, aid conditions, enrollment deposits, and decision deadlines directly with each institution before making a commitment.</p></section>}
