"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Plan = {id:string;title:string;interview_type:"Scholarship"|"College Admissions"|"Job"|"Internship";organization:string;interview_date:string|null;format:"In Person"|"Virtual"|"Phone";interviewer:string;questions_to_ask:string;notes:string;follow_up_date:string|null;checklist:Record<string,boolean>};
type Practice = {id:string;preparation_id:string;practiced_at:string;question:string;situation:string;task:string;action:string;result:string;reflection:string;confidence:number};
const checks=[["research","Research the organization or program"],["questions","Prepare questions to ask"],["star","Practice a STAR response"],["technology","Test technology or confirm directions"],["outfit","Choose interview-ready clothing"],["thankYou","Send a thank-you note afterward"]];
const emptyPlan=():Plan=>({id:"",title:"My Interview",interview_type:"Scholarship",organization:"",interview_date:null,format:"In Person",interviewer:"",questions_to_ask:"",notes:"",follow_up_date:null,checklist:{}});
const common:Record<Plan["interview_type"],string[]>={Scholarship:["Why are you a strong candidate?","How have you served your community?","What are your career goals?"],"College Admissions":["Why are you interested in this college?","What will you contribute to campus?","What academic interest do you want to explore?"],Job:["Tell me about yourself.","Describe a time you worked on a team.","How do you prioritize responsibilities?"],Internship:["Why does this internship interest you?","What skill do you want to develop?","Describe a time you took initiative."]};

export function InterviewPreparationCenter({userId}:{userId:string}){
  const [plans,setPlans]=useState<Plan[]>([]),[plan,setPlan]=useState<Plan>(emptyPlan()),[sessions,setSessions]=useState<Practice[]>([]);
  const [message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const [practice,setPractice]=useState({question:common.Scholarship[0],situation:"",task:"",action:"",result:"",reflection:"",confidence:3});
  useEffect(()=>{Promise.all([
    supabase.from("interview_preparations").select("*").eq("user_id",userId).order("updated_at",{ascending:false}),
    supabase.from("interview_practice_sessions").select("*").eq("user_id",userId).order("practiced_at",{ascending:false})
  ]).then(([p,s])=>{const loaded=(p.data??[]) as Plan[];setPlans(loaded);if(loaded[0])setPlan(loaded[0]);setSessions((s.data??[]) as Practice[])})},[userId]);
  const update=(p:Partial<Plan>)=>setPlan({...plan,...p});
  async function save(){setBusy(true);const payload={user_id:userId,title:plan.title.trim()||"My Interview",interview_type:plan.interview_type,organization:plan.organization,interview_date:plan.interview_date||null,format:plan.format,interviewer:plan.interviewer,questions_to_ask:plan.questions_to_ask,notes:plan.notes,follow_up_date:plan.follow_up_date||null,checklist:plan.checklist,updated_at:new Date().toISOString()};const q=plan.id?supabase.from("interview_preparations").update(payload).eq("id",plan.id):supabase.from("interview_preparations").insert(payload);const {data,error}=await q.select().single();setBusy(false);if(error)return setMessage(error.message);const saved=data as Plan;setPlan(saved);setPlans(plan.id?plans.map(x=>x.id===saved.id?saved:x):[saved,...plans]);setMessage("Interview plan saved privately.")}
  async function remove(){if(!plan.id)return;const {error}=await supabase.from("interview_preparations").delete().eq("id",plan.id);if(error)return setMessage(error.message);const rest=plans.filter(x=>x.id!==plan.id);setPlans(rest);setPlan(rest[0]??emptyPlan());setMessage("Interview plan removed.")}
  async function addPractice(e:FormEvent){e.preventDefault();if(!plan.id)return setMessage("Save the interview plan before recording practice.");setBusy(true);const {data,error}=await supabase.from("interview_practice_sessions").insert({user_id:userId,preparation_id:plan.id,...practice}).select().single();setBusy(false);if(error)return setMessage(error.message);setSessions([data as Practice,...sessions]);setPractice({...practice,situation:"",task:"",action:"",result:"",reflection:""});setMessage("Practice session recorded.")}
  async function removePractice(id:string){const {error}=await supabase.from("interview_practice_sessions").delete().eq("id",id);if(error)return setMessage(error.message);setSessions(sessions.filter(x=>x.id!==id))}
  const history=sessions.filter(x=>x.preparation_id===plan.id);
  return <section className="interview-center" id="interviews">
    <div className="interview-heading"><div><span className="kicker dark">INTERVIEW PREPARATION CENTER</span><h2>Practice with purpose. Walk in prepared.</h2><p>Create private plans for scholarship, college, job, and internship interviews.</p></div><div className="interview-actions"><button onClick={()=>setPlan(emptyPlan())}>New plan</button><button className="primary" onClick={save} disabled={busy}>{busy?"Saving…":"Save plan"}</button></div></div>
    <div className="interview-toolbar"><label>Plan<select value={plan.id} onChange={e=>setPlan(plans.find(x=>x.id===e.target.value)??emptyPlan())}><option value="">Unsaved plan</option>{plans.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Plan name<input value={plan.title} maxLength={120} onChange={e=>update({title:e.target.value})}/></label><label>Type<select value={plan.interview_type} onChange={e=>update({interview_type:e.target.value as Plan["interview_type"]})}><option>Scholarship</option><option>College Admissions</option><option>Job</option><option>Internship</option></select></label><label>Format<select value={plan.format} onChange={e=>update({format:e.target.value as Plan["format"]})}><option>In Person</option><option>Virtual</option><option>Phone</option></select></label></div>
    {message&&<div className="form-message" role="status">{message}</div>}
    <div className="interview-grid"><div className="interview-plan"><div className="two-col"><label>Organization or college<input value={plan.organization} onChange={e=>update({organization:e.target.value})}/></label><label>Interviewer<input value={plan.interviewer} onChange={e=>update({interviewer:e.target.value})}/></label><label>Interview date<input type="datetime-local" value={plan.interview_date?.slice(0,16)??""} onChange={e=>update({interview_date:e.target.value||null})}/></label><label>Follow-up reminder<input type="date" value={plan.follow_up_date??""} onChange={e=>update({follow_up_date:e.target.value||null})}/></label></div><label>Questions I want to ask<textarea value={plan.questions_to_ask} onChange={e=>update({questions_to_ask:e.target.value})}/></label><label>Notes<textarea value={plan.notes} onChange={e=>update({notes:e.target.value})}/></label><div className="interview-checklist"><b>Preparation checklist · {checks.filter(([key])=>plan.checklist[key]).length}/{checks.length}</b>{checks.map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(plan.checklist[key])} onChange={e=>update({checklist:{...plan.checklist,[key]:e.target.checked}})}/>{label}</label>)}</div><button className="danger" onClick={remove} disabled={!plan.id}>Delete plan</button></div>
    <aside className="interview-guide"><h3>Questions to practice</h3>{common[plan.interview_type].map(q=><button type="button" key={q} onClick={()=>setPractice({...practice,question:q})}>{q}</button>)}<h3>Interview essentials</h3><p><b>STAR:</b> explain the Situation, Task, Action you took, and Result.</p><p><b>Virtual:</b> test sound, camera, lighting, internet, and the meeting link.</p><p><b>Dress:</b> choose clean, comfortable clothing appropriate for the setting.</p><p><b>Thank-you:</b> send a brief, specific note within 24 hours when appropriate.</p></aside></div>
    <form className="star-practice" onSubmit={addPractice}><span className="kicker dark">STAR PRACTICE</span><h3>Build a response from your own experience.</h3><label>Practice question<input required value={practice.question} onChange={e=>setPractice({...practice,question:e.target.value})}/></label><div className="star-grid">{(["situation","task","action","result"] as const).map(field=><label key={field}>{field[0].toUpperCase()+field.slice(1)}<textarea value={practice[field]} onChange={e=>setPractice({...practice,[field]:e.target.value})}/></label>)}</div><div className="practice-footer"><label>Reflection<input value={practice.reflection} onChange={e=>setPractice({...practice,reflection:e.target.value})}/></label><label>Confidence<select value={practice.confidence} onChange={e=>setPractice({...practice,confidence:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><button className="primary" disabled={busy}>Record practice</button></div></form>
    {history.length>0&&<div className="practice-history"><h3>Practice history</h3>{history.map(s=><article key={s.id}><div><b>{s.question}</b><span>{s.practiced_at} · Confidence {s.confidence}/5</span></div><p>{s.reflection||"No reflection recorded."}</p><button className="danger" onClick={()=>removePractice(s.id)}>Remove</button></article>)}</div>}
  </section>
}
