"use client";
import {useEffect,useState} from "react";
type School={id:number;name:string;city:string;state:string};
export function SchoolPicker({value,onChange}:{value:string[];onChange:(schools:string[])=>void}){
 const[query,setQuery]=useState(""),[results,setResults]=useState<School[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(query.trim().length<2){setResults([]);return}const controller=new AbortController(),timer=setTimeout(async()=>{setLoading(true);setMessage("");try{const r=await fetch(`/api/schools?q=${encodeURIComponent(query)}`,{signal:controller.signal});const b=await r.json();setResults(b.schools??[]);if(!r.ok)setMessage(b.error??"School search is unavailable.")}catch(e){if((e as Error).name!=="AbortError")setMessage("School search is unavailable.")}finally{setLoading(false)}},300);return()=>{clearTimeout(timer);controller.abort()}},[query]);
 function add(name:string){if(!value.includes(name))onChange([...value,name]);setQuery("");setResults([])}function remove(name:string){onChange(value.filter(x=>x!==name))}
 return <div className="school-picker"><label>Schools of interest <span>(search the U.S. Department of Education directory)</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Start typing a college or school name" autoComplete="off"/></label>{loading&&<small>Searching schools…</small>}{message&&<small role="status">{message}</small>}{results.length>0&&<div className="school-results" role="listbox">{results.map(s=><button type="button" key={s.id} onClick={()=>add(s.name)}><b>{s.name}</b><span>{s.city}, {s.state}</span></button>)}</div>}<div className="selected-schools">{value.map(name=><span key={name}>{name}<button type="button" onClick={()=>remove(name)} aria-label={`Remove ${name}`}>×</button></span>)}</div><label>Other program or career <span>(optional)</span><div className="manual-school"><input placeholder="Type a program, career, or school not found above" onKeyDown={e=>{if(e.key==="Enter"&&e.currentTarget.value.trim()){e.preventDefault();add(e.currentTarget.value.trim());e.currentTarget.value=""}}}/><small>Press Enter to add. Commas and punctuation are allowed.</small></div></label></div>
}
